config/routes.rb
Rails.application.routes.draw do

  get 'products/index'

  get 'products/:slug' => 'products#show', as: 'product'

  get 'admin' => 'admin/companies#index'

  namespace :admin do
    resources :companies
    resources :services
    resources :contacts
    resources :blogs
    resources :products
    resources :pictures
  end

  get '/contact' => "contact#index", as: 'contact'
  post '/contact' => "contact#create"
  get '/blogs' => "blogs#index", as: 'blog'

  get '/services' => "services#index", as: 'services'

  get '/products' => "products#index", as: 'products'
  get '/designs' => "designs#index", as: 'designs'

  get '/about' => "about#index", as: 'about'
  root 'home#index'

end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id          :integer          not null, primary key
#  name        :string
#  parent_id   :integer
#  created_at  :datetime
#  updated_at  :datetime
#  description :text
#  sub_service :text
#  image_url   :string(2083)     default("--- []\n")
#  icon        :string
#

class Service < ActiveRecord::Base
  validates :name, presence: true
  has_many :images
  accepts_nested_attributes_for :images
  translates :name, :description, :sub_service
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < AdminController
  before_filter :find_model , only: [:update, :edit, :destroy]

  def index
    @service = Service.new
    @services = Service.all.order('id ASC')
  end

  def edit

  end

  def update
    if @service.update_attributes(params_update)
      redirect_via_turbolinks_to admin_services_path
    else
      render :edit
    end
  end

  def create
    @service = Service.create(params_update)
    flash[:notice] = "Success create service"
  end

  def destroy
    @id = @service.id
    @service.destroy
  end

  private

  def params_update
    params.require(:service)
      .permit(
        :name,
        :sub_service,
        :description,
        :image_url,
        :icon)
  end

  def find_model
    @service = Service.find(params[:id])
  end
end

app/controllers/services_controller.rb
# == Schema Information
#
# Table name: services
#
#  id          :integer          not null, primary key
#  name        :string
#  parent_id   :integer
#  created_at  :datetime
#  updated_at  :datetime
#  description :text
#  sub_service :text
#  image_url   :string(2083)     default("--- []\n")
#  icon        :string
#

class ServicesController < ApplicationController


  def index
    add_breadcrumb I18n.t('menu.home'), :root_path
    add_breadcrumb I18n.t('menu.service'), :services_path
    @services = Service.all.order('id ASC')
  end
end

app/views/admin/services/_form.html.erb
<%= semantic_form_for @service,
  url: @service.new_record? ? admin_services_path : admin_service_path(@service),
  remote: true,
  html: { :class => 'form-horizontal' } do |f| %>
  <%= f.semantic_errors %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :sub_service, input_html: { style: 'height: 80px'} %>
    <%= f.input :description, input_html: { style: 'height: 100px'}  %>
    <%= f.input :image_url %>
    <%= f.input :icon %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, wrapper_html: { class: 'btn btn-success' } %>
    <%= f.action :cancel, :as => :link %>
  <% end %>
<% end %>

app/views/admin/services/_service.html.erb
<tr id="service-<%= service.id %>">
  <td>
    <%= service.name %>
  </td>
  <td>
    <%= link_to 'Edit', edit_admin_service_path(service.id),
      class: 'btn btn-success' %>
    <%= link_to 'Delete', admin_service_path(service.id), method: :delete,
      remote: true,
      class: 'btn btn-danger',
      data: {confirm: "Are you sure?"} %>
  </td>
</tr>

app/views/admin/services/create.js.erb
$("table#services tbody").prepend("<%=j render 'service', service: @service %>")
$('#new_service')[0].reset()

app/views/admin/services/destroy.js.erb
$("tr#service-<%= @id %>").remove()

app/views/admin/services/edit.html.erb
<div class="container" style="margin-top: 100px">
  <%= flash_messages %>
  <div class="row">
    <%= render 'shared/admin_menu' %>
    <div class="col-sm-8">
      <%= render 'form' %>
    </div>
  </div>
  <div style="height: 50px;"></div>
  
</div>

app/views/admin/services/index.html.erb
<div class="container" style="margin-top: 100px">
  <%= flash_messages %>
  <div class="row">
    <%= render 'shared/admin_menu' %>
    <div class="col-sm-8">
      <%= render 'form' %>
    </div>
  </div>

  <div class="row">
    <table id="services" class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <%=  render partial: 'service', collection: @services %>
      </tbody>
    </table>
  <div style="height: 50px;"></div>
    
  </div>
</div>

app/views/admin/services/update.js.erb
update.js.erb