config/routes.rb
Rails.application.routes.draw do

  get 'products/index'

  get 'products/:slug' => 'products#show', as: 'product'

  get 'admin' => 'admin/companies#index'

  namespace :admin do
    resources :companies
    resources :services
    resources :contacts
    resources :blogs
    resources :products
    resources :pictures
  end

  get '/contact' => "contact#index", as: 'contact'
  post '/contact' => "contact#create"
  get '/blogs' => "blogs#index", as: 'blog'

  get '/services' => "services#index", as: 'services'

  get '/products' => "products#index", as: 'products'
  get '/designs' => "designs#index", as: 'designs'

  get '/about' => "about#index", as: 'about'
  root 'home#index'

end

app/views/shared/_admin_menu.html.erb
<div class="col-sm-3">
  <div style="">
    <ul class="nav nav-pills nav-stacked">
      <%= li_active_link 'Company', admin_companies_path  %>
      <%= li_active_link 'Picture', admin_pictures_path  %>
      <%= li_active_link 'Services', admin_services_path  %>
      <%= li_active_link 'Products', admin_products_path  %>
      <%= li_active_link 'Contacts', admin_contacts_path  %>
      <%= li_active_link 'Blogs', admin_blogs_path  %>
    </ul>
  </div>
</div>

app/views/shared/_footer.html.erb
  <footer>
    <div class="footer">
      <div class="container">
        <div class="social-icon">
          <div class="col-md-4">
            <ul class="social-network">
              <li><%= link_to_if @company.facebook.present?, "<i class='fa fa-facebook'></i>".html_safe, @company.facebook, class: 'fb tool-tip', title: 'Facebook', target:  '_blank' %>
              </li>
              <li>
                <%= link_to_if @company.twiter.present?, "<i class='fa fa-twitter'></i>".html_safe, @company.twiter, class: 'twitter tool-tip', title: 'Twitter', target:  '_blank' %>
              </li>
              <li>
                <%= link_to_if @company.google_plus.present?, "<i class='fa fa-google-plus'></i>".html_safe, @company.google_plus, class: 'gplus tool-tip', title: 'Google Plus', target:  '_blank' %>
              </li>
              <li>
                <%= link_to_if @company.linkedin.present?, "<i class='fa fa-linkedin'></i>".html_safe, @company.linkedin, class: 'linkedin tool-tip', title: 'Linkedin', target:  '_blank' %>
              <li>
                <%= link_to_if @company.youtube.present?, "<i class='fa fa-youtube-play'></i>".html_safe, @company.youtube, class: 'ytube tool-tip', title: 'YouTube', target:  '_blank' %>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-4 col-md-offset-4">
          <div class="copyright">
            &copy; June  2015 by Miền Đông & Tây Nguyên. All Rights Reserved.
          </div>
        </div>
      </div>

    <div class="pull-right">
      <a href="#home" class="scrollup"><i class="fa fa-angle-up fa-3x"></i></a>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div class="container">
  <div class="row box-header hidden-xs">
    <div class="col-sm-3 box-logo">
      <a href="/" >
        <div>
          <%= image_tag 'logo.jpg'%>
        </div>
        <div class="text-logo">MIỀN ĐÔNG & TÂY NGUYÊN</div>
      </a>
    </div>
    <div class="col-sm-3">
      <div class="box-address">
        <i class="fa fa-map-marker" aria-hidden="true"></i>
        <span class="street"> đường 11 </span>
        <span class="ward">Trường Thọ, Thủ Đức, TP.HCM</span>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="box-phone">
        <i class="fa fa-phone" aria-hidden="true"></i>
        <span class="phone">0979006996 - 0932702446</span>
        <span class="email">miendongtaynguyen@gmail.com</span>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="box-open-time">
        <i class="fa fa-clock-o" aria-hidden="true"></i>
        <span class="day">Thứ 2 - Thứ 7</span>
        <span class="hour">08:00 - 17:00</span>
      </div>
    </div>
  </div>
</div>

<nav class="navbar navbar-default header js_navbar_top">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand hidden-sm hidden-md hidden-lg" href="/">
      <%= image_tag 'logo.jpg' %>
    </a>
  </div>
  <div class="container">
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li role="presentation">
          <%= active_link_to t('menu.home'), root_path %>
        </li>
        <li role="presentation">
          <%= active_link_to t('menu.about'), about_path %>
        </li>
        <li role="presentation">
          <%= active_link_to t('menu.design'), designs_path %>
        </li>
        <li role="presentation">
          <%= active_link_to t('menu.products'), products_path %>
        </li>
       <!--  <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= t('menu.products') %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= active_link_to t('menu.products_working'), "#{products_path}?status=working" %>
            </li>
            <li>
              <%= active_link_to t('menu.products_complete'), "#{products_path}?status=completed" %>
            </li>
          </ul>
        </li> -->
        <li role="presentation">
          <%= active_link_to t('menu.service'), services_path %>
        </li>
        <li role="presentation">
          <%= active_link_to t('menu.blog'), blog_path %>
        </li>
        <li role="presentation">
          <%= active_link_to t('menu.contact'), contact_path,  'data-no-turbolink' => true %>
        </li>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t("menu.#{I18n.locale}") %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if I18n.locale != :vn %>
            <li>
              <%= link_to t('menu.vn'), current_url(locale: 'vn') %>
            </li>
            <% end %>

            <% if I18n.locale != :en %>
            <li>
              <%= link_to t('menu.en'), current_url(locale: 'en') %>
            </li>
            <% end %>
          </ul>
        </li> -->
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_main_slider.html.erb
<div id="myCarousel" class="carousel slide hidden-xs" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="<%= @company.background_url %>" alt="Chania">
      <div class="carousel-caption">
        <h3>CÔNG TY TNHH THIẾT KẾ XÂY DỰNG</h3>
        <p>MIỀN ĐÔNG VÀ TÂY NGUYÊN</p>
      </div>
    </div>

    <div class="item">
      <img src="<%= @company.background_url %>" alt="Chania">
      <div class="carousel-caption">
        <h3>CÔNG TY TNHH THIẾT KẾ XÂY DỰNG</h3>
        <p>MIỀN ĐÔNG VÀ TÂY NGUYÊN</p>
      </div>
    </div>

    <div class="item">
      <img src="<%= @company.background_url %>" alt="Flower">
      <div class="carousel-caption">
        <h3>CÔNG TY TNHH THIẾT KẾ XÂY DỰNG</h3>
        <p>MIỀN ĐÔNG VÀ TÂY NGUYÊN</p>
      </div>
    </div>
  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="fa fa-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="fa fa-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_service.html.erb
<div class="col-md-3">
  <div class="hi-icon-wrap hi-icon-effect wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms" >
    <i class="fa <%= service.icon %>"></i>
    <h2><%= service.name %></h2>
    <!-- <p><%= simple_format(service.sub_service) %></p> -->
  </div>
</div>

app/views/shared/_slide_footer.html.erb
_slide_footer.html.erb