config/routes.rb
Rails.application.routes.draw do

  get 'products/index'

  get 'products/:slug' => 'products#show', as: 'product'

  get 'admin' => 'admin/companies#index'

  namespace :admin do
    resources :companies
    resources :services
    resources :contacts
    resources :blogs
    resources :products
    resources :pictures
  end

  get '/contact' => "contact#index", as: 'contact'
  post '/contact' => "contact#create"
  get '/blogs' => "blogs#index", as: 'blog'

  get '/services' => "services#index", as: 'services'

  get '/products' => "products#index", as: 'products'
  get '/designs' => "designs#index", as: 'designs'

  get '/about' => "about#index", as: 'about'
  root 'home#index'

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                  :integer          not null, primary key
#  name                :string
#  description         :text
#  company_id          :integer
#  service_id          :integer
#  service_name        :string
#  created_at          :datetime
#  updated_at          :datetime
#  image_url           :string(2083)
#  summary_description :text
#  status              :integer
#  slug                :string
#  main_product        :boolean
#  product_type_id     :integer
#  image_thumb         :string
#

class Product < ActiveRecord::Base
  enum status: [ :working, :completed]
  belongs_to :company
  belongs_to :product_type
  has_many :images

  scope :design, -> { where(product_type_id: ProductType.find_by(name: 'Thiết kế').id) }
  scope :normal, -> { where(product_type_id: ProductType.find_by(name: 'Thi công').id) }

  translates :name, :description, :summary_description

  accepts_nested_attributes_for :images, :reject_if => :all_blank, :update_only => true, :allow_destroy => true

  before_save :generate_slug

  private

  def generate_slug
    self.slug = remove_accent(self.name).parameterize if I18n.locale == :vn
  end

  ## Convert Vietnamese to no marks
  def remove_accent(source)
    unicode = {
      'a'=>/á|à|ả|ã|ạ|ă|ắ|ặ|ằ|ẳ|ẵ|â|ấ|ầ|ẩ|ẫ|ậ/,
      'd'=>/đ/,
      'e'=>/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/,
      'i'=>/í|ì|ỉ|ĩ|ị/,
      'o'=>/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/,
      'u'=>/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/,
      'y'=>/ý|ỳ|ỷ|ỹ|ỵ/,
      'A'=>/Á|À|Ả|Ã|Ạ|Ă|Ắ|Ặ|Ằ|Ẳ|Ẵ|Â|Ấ|Ầ|Ẩ|Ẫ|Ậ/,
      'D'=>/Đ/,
      'E'=>/É|È|Ẻ|Ẽ|Ẹ|Ê|Ế|Ề|Ể|Ễ|Ệ/,
      'I'=>/Í|Ì|Ỉ|Ĩ|Ị/,
      'O'=>/Ó|Ò|Ỏ|Õ|Ọ|Ô|Ố|Ồ|Ổ|Ỗ|Ộ|Ơ|Ớ|Ờ|Ở|Ỡ|Ợ/,
      'U'=>/Ú|Ù|Ủ|Ũ|Ụ|Ư|Ứ|Ừ|Ử|Ữ|Ự/,
      'Y'=>/Ý|Ỳ|Ỷ|Ỹ|Ỵ/,
      "-"=>/[^a-zA-Z\d]/
      }
    unless source.nil?
      unicode.each do |nonUni, uni|
        source = source.rstrip
        source = source.lstrip
        source = source.gsub(/ +/, " ")
        source = source.gsub(uni, nonUni)
        source = source.gsub(/-+/,"-")
      end
      source.downcase
    end
  end
end

app/models/product_type.rb
# == Schema Information
#
# Table name: product_types
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ProductType < ActiveRecord::Base
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :find_model, only: [:update, :edit, :destroy]
  before_action :services, only: [:index, :edit]

  def index
    company = Company.first
    @product = Product.new(company_id: company.id)
    1.times { @product.images.build }
    @products = Product.all.order('id DESC')
    @product_typies = ProductType.all
  end

  def edit
    @product.images.build if @product.images.blank?
    @product_typies = ProductType.all
  end

  def update
    if @product.update_attributes(params_update)
      redirect_via_turbolinks_to admin_products_path
    else
      render :edit
    end
  end

  def create
    @product = Product.create(params_update)
    flash[:notice] = "Success create product"
  end

  def destroy
    @id = @product.id
    @product.destroy
  end

  private

  def params_update
    params.require(:product)
      .permit(
        :name,
        :description,
        :summary_description,
        :image_url,
        :image_thumb,
        :status,
        :company_id,
        :product_type_id,
        :main_product,
        images_attributes: [:_destroy, :id, :title, :url, :url_thumb, :position]
      )
  end

  def find_model
    @product = Product.find(params[:id])
  end

  def services
    @services_collections = Service.all.pluck(:name, :id)
  end

end

app/controllers/products_controller.rb
# == Schema Information
#
# Table name: products
#
#  id                  :integer          not null, primary key
#  name                :string
#  description         :text
#  company_id          :integer
#  service_id          :integer
#  service_name        :string
#  created_at          :datetime
#  updated_at          :datetime
#  image_url           :string(2083)
#  summary_description :text
#  status              :integer
#  slug                :string
#  main_product        :boolean
#  product_type_id     :integer
#  image_thumb         :string
#

class ProductsController < ApplicationController

  def index
    add_breadcrumb I18n.t('menu.home') , :root_path
    breadcrumb_products(params[:status])
    @products_working = Product.working.normal
    @products_completed = Product.completed.normal

  end

  def show
    @product  = Product.find_by(slug: params[:slug])
    add_breadcrumb I18n.t('menu.home') , :root_path
    breadcrumb_products(@product.status)
    add_breadcrumb @product.name,  product_path(@product.slug)
  end

  private
  def breadcrumb_products(status)
    if status == "working"
      add_breadcrumb "#{I18n.t('menu.products')} #{I18n.t('menu.products_working')}",  products_path(status: 'working')
    elsif status == "completed"
      add_breadcrumb "#{I18n.t('menu.products')} #{I18n.t('menu.products_complete')}",  products_path(status: 'working')
    else
      add_breadcrumb I18n.t('menu.products'), products_path
    end
  end
end

app/views/admin/products/_form.html.erb
<%= semantic_form_for @product,
  url: @product.new_record? ? admin_products_path : admin_product_path(@product),
  remote: true,
  html: { :class => 'form-horizontal' } do |f| %>
  <%= f.semantic_errors %>
  <div class="row">

  </div>
  Images <span class="pull-right"><button id="add_image" type="button" class="btn btn-success text-right">Add Image</button></span>

  <hr/>
  <div id="images">
    <%= f.semantic_fields_for :images do |h| %>
      <div id="panel_image_<%= h.index %>" class="panel panel-info">
        <div class="panel-heading">Image <%= h.index + 1 %> <span class="pull-right"><button type="button" data-id="<%= h.index %>" class="del-image btn btn-danger btn-sm">Del</button></span></div>
        <div class="panel-body">
          <%= h.input :_destroy, as: :hidden %>
          <%= h.input :title %>
          <%= h.input :url_thumb %>
          <%= h.input :url %>
          <%= h.input :position %>
        </div>
      </div>

    <% end %>
  </div>
  Information
  <hr/>
  <%= f.inputs do %>
    <%= f.input :company_id, as: :hidden %>
    <%= f.input :name %>
    <%= f.input :summary_description,  :input_html => { :class => 'autogrow', :rows => 5, :cols => 20} %>
    <%= f.input :image_url %>
    <%= f.input :image_thumb %>
    <%= f.input :status, as: :select, collection: options_for_select(Product.statuses.keys, f.object.status.to_s) %>
    <%= f.input :main_product %>
    <%= f.input :product_type_id, as: :select, collection: @product_typies %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, wrapper_html: { class: 'btn btn-success' } %>
    <%= f.action :cancel, :as => :link %>
  <% end %>
<% end %>
 <script>
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.xc
    CKEDITOR.editorConfig = function( config ){
          // Define changes to default configuration here. For example:
          // config.language = 'fr';
          // config.uiColor = '#AADC6E';
          config.height = '800px';
      };
    CKEDITOR.replace('product_summary_description',{
      height: '100px'
    });
</script>

app/views/admin/products/_product.html.erb
<tr id="product-<%= product.id %>">
  <td>
    <%= product.name %>
  </td>
  <td>
    <%= link_to 'Edit', edit_admin_product_path(product.id),
      class: 'btn btn-success' %>
    <%= link_to 'Delete', admin_product_path(product.id), method: :delete,
      remote: true,
      class: 'btn btn-danger',
      data: {confirm: "Are you sure?"} %>
  </td>
</tr>

app/views/admin/products/create.js.erb
$("table#products tbody").prepend("<%=j render 'product', product: @product %>")
$('#new_product')[0].reset()

app/views/admin/products/destroy.js.erb
$("tr#product-<%= @id %>").remove()

app/views/admin/products/edit.html.erb
<div class="container" style="margin-top: 100px">
  <%= flash_messages %>
  <div class="row">
    <%= render 'shared/admin_menu' %>
    <div class="col-sm-8">
      <%= render 'form' %>
    </div>
  </div>
  <div style="height: 50px;"></div>

</div>

app/views/admin/products/index.html.erb
<div class="container" style="margin-top: 100px">
  <%= flash_messages %>
  <div class="row">
    <%= render 'shared/admin_menu' %>
    <div class="col-sm-9">
      <%= render 'form' %>
    </div>
  </div>

  <div class="row">
    <table id="products" class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <%=  render partial: 'product', collection: @products %>
      </tbody>
    </table>
  <div style="height: 50px;"></div>

  </div>
</div>

app/views/admin/products/update.js.erb
alert('Success update');